### ISSUE TITLE
build error npm install

### ISSUE THREAD

**Issue by binderth** [zachcheatham/rnet-pi#1]
Hi, 
thanks for the nice work, tried to install, but got the following info:
```
[10:51:37] openhabian@openHAB-Music:~/rnet-pi$ sudo npm install

> mdns@2.5.1 install /home/openhabian/rnet-pi/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES current user ("openhabian") does not have permission to access the dev dir "/root/.cache/node-gyp/12.19.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/openhabian/rnet-pi/node_modules/mdns/.node-gyp"
make: Entering directory '/home/openhabian/rnet-pi/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:177: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/openhabian/rnet-pi/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.51-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/openhabian/rnet-pi/node_modules/mdns
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN rnet-proxy@1.0.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-30T09_52_54_686Z-debug.log
```

is there something I can do for this?

running on a RPI on
```
##   Release = Raspbian GNU/Linux 10 (buster)
##    Kernel = Linux 5.4.51-v7+
##  Platform = Raspberry Pi 3 Model B Rev 1.2

nodejs is already the newest version (12.19.0-1nodesource1).
```

**Comment by zachcheatham** [comment]
It looks like everytime I've run install, I've had the mdns package already installed one way or another. Run `sudo apt install libavahi-compat-libdnssd-dev` and then attempt `npm install` again. I need to include that in the install instructions and possibly package this a little bit better.
